[book]
title = "Rust"
authors = ["sabertazimi"]
description = "Rust labs and notes."
src = "docs/rust"
language = "zh-CN"

[output.html]
git-repository-url = "https://github.com/sabertazimi/lab"
edit-url-template = "https://github.com/sabertazimi/lab/edit/main/{path}"
site-url = "/rust/"

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
